import Header from '../components/header';
import Footer from '../components/footer';
import TopBanner from '../components/common/top-banner';
import type { Metadata } from 'next';
import '../assets/css/globals.css';

export const metadata: Metadata = {
	title: 'SHOP.CO',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en">
			<body className="text-[14px] md:text-[16px]">
				<TopBanner />
				<Header />
				{children}
				<Footer />
			</body>
		</html>
	);
}
