import Header from './components/header';
import Footer from './components/footer';
import PopUp from './components/common/pop-up';
import type { Metadata } from 'next';
import './globals.css';

export const metadata: Metadata = {
	title: 'SHOP.CO',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en">
			<body className={'text-sm lg:text-base'}>
        <PopUp />
				<Header />
				{children}
				<Footer />
			</body>
		</html>
	);
}
